on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: k8sregistrymax.azurecr.io
        username: ${{ secrets.acr_k8sregistrymax_username }}
        password: ${{ secrets.acr_k8sregistrymax_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t k8sregistrymax.azurecr.io/k8sccluster:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push k8sregistrymax.azurecr.io/k8sccluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sccluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8sc_clusteraff4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8sc_clusteraff4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8sc_clusteraff4
        container-registry-url: k8sregistrymax.azurecr.io
        container-registry-username: ${{ secrets.acr_k8sregistrymax_username }}
        container-registry-password: ${{ secrets.acr_k8sregistrymax_password }}
        secret-name: k8scclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8sc_clusteraff4
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          k8sregistrymax.azurecr.io/k8sccluster:${{ github.sha }}
        imagepullsecrets: |
          k8scclusterdockerauth
